#!/usr/local/bin/lua

local query = arg[1]
if (string.find(query, " ")) then
	print("I'm sorry to tell you that this script could not translate a sentence.\n")
	return
end
os.execute("curl -so '/tmp/translate.tmp' http://dict.youdao.com/search?q="..query)
io.input("/tmp/translate.tmp")
local file = io.read("*all")
local data = string.match(file, "<div class=%ptrans%-container.-</div>")
data = string.match(data, "<ul>.*</ul>")
print("\t" .. query)
for f in string.gmatch(data, "<li>(.-)</li>") do
	print("\t".. f)
end
